development:
  secret_token: ENV["DEV_SECRET_TOKEN"]
  secret_key_base: ENV["DEV_SECRET_KEY_BASE"]

production:
  secret_token: ENV["PROD_SECRET_TOKEN"]
  secret_key_base: ENV["PROD_SECRET_KEY_BASE"]
